name: Sync to Gitee

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the GitHub repos to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/Bowen-0x00
          dst: gitee/Bowen-0x00
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          account_type: user
          force_update: true
          static_list: '${{ github.event.repository.name }}'